{{- if .Values.deploy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "common.names.fullname" .) .Values.deploy.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations: {{- .Values.deploy.serviceAccount.annotations | toYaml | nindent 4 }}
{{- end -}}