apiVersion: v2
name: test-chart
description: A test chart to validate the common library
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: common
  version: "0.3.0"
  repository: "file://../"